ignored = [
  "github.com/gopherjs/gopherjs/js",
]

required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/johanbrandhorst/protobuf/protoc-gen-gopherjs",
  "github.com/foobaz/go-zopfli",
]

[prune]
  non-go = true
  unused-packages = true
  go-tests = true

  [[prune.project]]
    name = "github.com/johanbrandhorst/protobuf"
    non-go = false

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  name = "github.com/johanbrandhorst/protobuf"
  version = "0.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/improbable-eng/grpc-web"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/vfsgen"
